#pragma once

struct Tag {
    int tag;
    const char *meaning;
};

// Classic Duke Nukem 3D / Atomic Edition Sector Effector lotags (tile 1).
// https://wiki.eduke32.com/wiki/Sector_Effector_Reference_Guide
constexpr Tag sectorEffectorLotags[] = {
    {0, "Sector rotation"},
    {1, "Rotation pivot"},
    {2, "Earthquake"},
    {3, "Shot-triggered flicker"},
    {4, "Flickering lights"},
    {5, "Boss sector (unfinished)"},
    {6, "Subway engine"},
    {7, "Teleport"},
    {8, "Door lighting: up"},
    {9, "Door lighting: down"},
    {10, "Automatic door closing"},
    {11, "Swinging door"},
    {12, "Switched lighting"},
    {13, "Explosive sector"},
    {14, "Subway carriage"},
    {15, "Sliding door"},
    {16, "Reactor rotation (unfinished)"},
    {17, "Transport elevator"},
    {18, "Incremental vertical movement"},
    {19, "Explosion-triggered ceiling drop"},
    {20, "Stretching bridge"},
    {21, "Dropping floor"},
    {22, "Teeth-door component"},
    {23, "One-way teleport exit"},
    {24, "Conveyor / current"},
    {25, "Piston ceiling"},
    {26, "Escalator (unfinished)"},
    {27, "Demo viewpoint"},
    {28, "Lightning generator"},
    {29, "Waves"},
    {30, "Shuttle train"},
    {31, "Moving floor"},
    {32, "Moving ceiling"},
    {33, "Quake debris"},
    {34, "Alternate conveyor (undocumented)"},
    {35, "Drill (unfinished)"},
    {36, "Projectile emitter"},
    {49, "Point light"},
    {50, "Spot light"},
};

// Sector tags are distinct from Sector Effector sprite tags.
// https://wiki.eduke32.com/wiki/Sector_Tag_Reference_Guide
constexpr Tag sectorLotags[] = {
    {0, "Normal sector"},
    {1, "Water surface"},
    {2, "Underwater"},
    {3, "Cycloid Emperor movement area"},
    {9, "Star Trek sliding doors"},
    {15, "Transport elevator"},
    {16, "Descending platform"},
    {17, "Ascending platform"},
    {18, "Elevator down"},
    {19, "Elevator up"},
    {20, "Ceiling door"},
    {21, "Floor door"},
    {22, "Vertically splitting door"},
    {23, "Hinged door"},
    {25, "Door sliding sideways"},
    {26, "Star Trek split door"},
    {27, "Stretching bridge"},
    {28, "Dropping floor / ceiling"},
    {29, "Teeth-door prong"},
    {30, "Bridge rotation and elevation"},
    {31, "Two-way train"},
    {10000, "Play sound 0 once (10000 + sound ID)"},
    {32767, "Secret area"},
    {65534, "End of level with message"},
    {65535, "Immediate end of exit"},
};

// Common Duke 3D / Atomic Edition sounds that can be assigned to MusicAndSFX.
// CON scripts and mods may define other sounds, so these are suggestions only.
constexpr Tag musicAndSfxLotags[] = {
    {0, "Kick hit"},
    {35, "Teleport"},
    {69, "Squished"},
    {70, "Teleporter"},
    {71, "Elevator starts"},
    {73, "Elevator stops"},
    {74, "Door"},
    {75, "Subway"},
    {76, "Switch (default)"},
    {79, "Toilet flush"},
    {81, "Earthquake"},
    {82, "Alarm"},
    {83, "Security monitor"},
    {84, "Engine"},
    {85, "Reactor"},
    {86, "Computer ambience"},
    {87, "Grinding gears"},
    {88, "Bubbles / water ambience"},
    {89, "Machine ambience"},
    {90, "Sewer ambience"},
    {91, "Wind ambience"},
    {92, "Dripping water"},
    {93, "Steam hissing"},
    {95, "Bar music"},
    {165, "Swinging door"},
    {166, "Ceiling door (soft)"},
    {167, "Ceiling door (sharp)"},
    {212, "Monitor / combination switch beep"},
    {252, "Duke mirror quote"},
    {256, "Space door (fast, soft hydraulic)"},
    {257, "Space door (slow, soft hydraulic)"},
    {258, "Space door (slow, hissing)"},
    {259, "Space door (fast, hissing)"},
    {260, "Space door (sharp hiss)"},
    {261, "Alien elevator / hydraulic door"},
    {262, "Vault door"},
    {286, "Alien door (screeching)"},
    {287, "Alien door (cyclic)"},
    {1000, "Echo effect (amount 0)"},
    {1024, "Echo effect (amount 24)"},
    {1064, "Echo effect (amount 64)"},
    {1128, "Echo effect (amount 128)"},
    {1255, "Echo effect (amount 255)"},
};
